apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rtmon-archify-dev
  namespace: mfsada
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rtmon-archify-sidecar
  namespace: mfsada
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 1Gi
